# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20161012_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/avatars'),
        ),
    ]
