# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_user_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_to',
        ),
    ]
