# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_subscriber_subscribed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
