# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_subscriber_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
