# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20151010_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='story',
            new_name='post',
        ),
    ]
