# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='guidelines',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
