# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='welcomepost',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
