# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='hub_type',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='users_can_create_children',
        ),
    ]
