# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0005_hub_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/backgrounds'),
        ),
    ]
