# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(default='', max_length=64)),
                ('prompt_type', models.CharField(blank=True, choices=[('prompt', 'Prompt'), ('wpsub', 'wpsub')], default='prompt', max_length=64)),
            ],
        ),
    ]
