# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(blank=True, choices=[('concept', 'Concept'), ('setting', 'Setting'), ('character', 'Character'), ('problem', 'Problem/Goal')], default='concept', max_length=64),
        ),
    ]
