# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='hubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
