# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0004_auto_20161008_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
