# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0006_hub_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hubs/backgrounds'),
        ),
    ]
