# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20160501_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wordcount',
            field=models.IntegerField(default=0),
        ),
    ]
