# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20161008_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='posts.Post'),
        ),
    ]
