# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(blank=True, choices=[('subscribe', 'Subscriber'), ('reply', 'Reply'), ('repost', 'Reply'), ('upvote', 'Upvote')], default=None, max_length=64)),
                ('isread', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='out_notifications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('to_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='in_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
