# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20160501_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_wordcount',
            field=models.IntegerField(default=250),
        ),
    ]
