# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_user_target_wordcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_subscribers',
            new_name='email_subscriber_notifications',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='email_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
