# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20160927_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='categories_to_import',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments_downvoted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments_upvoted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='user',
            name='downvoted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_messages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_subscriber_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_subscriptions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_upvotes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_dark_interface',
        ),
        migrations.RemoveField(
            model_name='user',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rational',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rss_feed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shadowban',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_wordcount',
        ),
    ]
