# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20161008_0141'),
        ('profiles', '0019_auto_20161008_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reposted',
            field=models.ManyToManyField(blank=True, related_name='reposters', to='posts.Post'),
        ),
    ]
